# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib D:/gkris/RISC-V/RISC-V.srcs/sources_1/new/single_cycle_riscv.v
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/gkris/RISC-V/RISC-V.cache/wt [current_project]
set_property parent.project_dir D:/gkris/RISC-V [current_project]
catch { write_hwdef -file single_cycle_riscv.hwdef }
synth_design -top single_cycle_riscv -part xc7a35tcpg236-1
write_checkpoint single_cycle_riscv.dcp
report_utilization -file single_cycle_riscv_utilization_synth.rpt -pb single_cycle_riscv_utilization_synth.pb
